---
title: mm-partner
timezone: America/New_York
collections:
  partner:
    title: Partner
    output: true
    permalink: "/:path/"
    lang: en
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
safe: false
source: app
exclude:
- assets/scripts
- assets/vendor
- assets/styles
- README.md
highlighter: false
domain: http://www.missingmaps.org
path_prefix: "/partners"
default_partner: all
